# Vendor for CM 11 (FLY IQ441) by JaMBy

LOCAL_PATH := /$(call my-dir)

include /$(CLEAR_VARS)
LOCAL_MODULE := libdrmmtkutil
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libdrmmtkutil.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libdpframework
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libdpframework.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libblisrc
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libblisrc.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libblisrc32
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libblisrc32.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libaudio.primary.default
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libaudio.primary.default.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

#include /$(CLEAR_VARS)
#LOCAL_MODULE := audio_policy.default
#LOCAL_MODULE_OWNER := $VENDOR
#LOCAL_SRC_FILES := lib/hw/audio_policy.default.so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/hw
#include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libaudiocompensationfilter
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libaudiocompensationfilter.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libaudiocomponentengine
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libaudiocomponentengine.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libmtklimiter
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libmtklimiter.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libmtkplayer
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libmtkplayer.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libaudiodcrflt
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libaudiodcrflt.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libvcodecdrv
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libvcodecdrv.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libstagefright_memutil
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libstagefright_memutil.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libvideoeditor_core
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libvideoeditor_core.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libvideoeditor_osal
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libvideoeditor_osal.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libvideoeditor_videofilters
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libvideoeditor_videofilters.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libvideoeditorplayer
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libvideoeditorplayer.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)

include /$(CLEAR_VARS)
LOCAL_MODULE := libMtkOmxFlacDec
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := lib/libMtkOmxFlacDec.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := /$(TARGET_OUT_SHARED_LIBRARIES)
include /$(BUILD_PREBUILT)
